### ISSUE TITLE
Preferences: size of edit box

### ISSUE THREAD

**Issue by iangreenleaf** [grinnellplans/GrinnellPlans#26]
Users can set the size their plan editing box appears as.

Honestly, I'm not convinced this feature is important to implement. May be better to set a sane default, and count on modern browsers allowing resizing of text inputs.

**Comment by annaswims** [comment]
Agreed.  I'd rather see it take up most of the page on whatever device I happen to be using, rather than a user setting.

**Comment by iangreenleaf** [comment]
Okay, let's drop this setting and use a sane default instead. Moving to #83.
