### ISSUE TITLE
BoardVote#vote should only accept 1 or -1

### ISSUE THREAD

**Issue by iangreenleaf** [grinnellplans/GrinnellPlans#52]
You won't be able to test this in a browser right now because the Notes interface isn't built. But you can write a couple simple unit tests as a great way of checking the behavior.

**Comment by PsychicNoodles** [comment]
Should be ready to close due to PR #128.

**Comment by iangreenleaf** [comment]
Oop, good catch, thanks. FYI you can put "Fixes #TICKETNUM" in your commit message or PR description and it will close automatically when merged.
