### ISSUE TITLE
"Planwatch" aka recently updated plans

### ISSUE THREAD

**Issue by iangreenleaf** [grinnellplans/GrinnellPlans#67]
This page needs to be created. You'll want to remove the placeholder for `recently_updated_plans` that I put in `routes.rb`.

**Comment by PsychicNoodles** [comment]
Is it fair to assume this is a GET-only resource?

**Comment by iangreenleaf** [comment]
Yep, seems like a fair assumption. You can use the existing Plans page for a reference. It's mostly just a paginated list of links.

**Comment by PsychicNoodles** [comment]
Considering including a pagination library, possibly [this one](https://github.com/mislav/will_paginate). Since we'll need pagination for things like search later it's probably rather significant which one is chosen.

**Comment by PsychicNoodles** [comment]
Also, I'm thinking the form that sets the hour range for recently updated plans should be GET, not POST. Nothing is actually set or persisted on changing, it only affects the current instance of the page.

**Comment by iangreenleaf** [comment]
We're actually already using [Kaminari](https://github.com/amatsuda/kaminari) which is worse-named but generally very well-liked. Search will be… fun, but that's a problem for later :D

**Comment by PsychicNoodles** [comment]
Ah, sorry, didn't notice. I'll use that, then.

**Comment by iangreenleaf** [comment]
> Also, I'm thinking the form that sets the hour range for recently updated plans should be GET, not POST. Nothing is actually set or persisted on changing, it only affects the current instance of the page.

Yep, that would be great. The PHP version was written before RESTful behavior was really a thing :)

Sometimes these things are POST because of [query string length limitations](http://stackoverflow.com/a/812962/58418), but that shouldn't be a problem with this form, so GET would be great.

**Comment by PsychicNoodles** [comment]
There's currently an issue related to disabling the `:recently_updated_plans` placeholder path. It causes the following error when loading the index page:

    undefined method `recently_updated_plans_path' for #<ActionDispatch::Routing::RoutesProxy:0x007faf65b908b8>

I have dug a little bit and think it might be related to the `AvailLink` model, which seems to have set of default values from a db migration file. This eventually feeds into the `_links.html.haml` file which tries to get the `path_helper` function value from each item in the table. This then presumably causes the error as `recently_updated_plans` is no longer a valid route.

The current idea I have is to update the `rails_helper` column for Planwatch, which according to the `avail_link.rb` is where that list of links is sourced from in the first place. I'll try that now and see if it works.

**Comment by iangreenleaf** [comment]
Sure, that will work. A perhaps easier way to do it without a DB migration is to set a route alias. So you could have something like this:

```ruby
  resources :plans do
    collection do
      get :recently_updated, as: :recently_updated_plans
      #…
```

**Comment by PsychicNoodles** [comment]
I tried doing that, but for whatever reason it gave the same error.

**Comment by iangreenleaf** [comment]
No worries, do whatever works for the moment and I can always poke at it once you put up a PR.
