### ISSUE TITLE
404 CSS

### ISSUE THREAD

**Issue by Gusbenz** [grinnellplans/GrinnellPlans#76]
Hi y'all,

My girlfriend went to Grinnell and she loves Plans, but she's having an issue with seeing your CSS file, as am I.

http://veronicaerb.com/plans/eversosimple.css 404s

**Comment by ianlunderskov** [comment]
hi gusbenz,

another user used it as well and posted a copy -- have her update the stylesheet URL to https://css.alexcohn.com/eversosimple.css

cheers,
ianL

**Comment by Gusbenz** [comment]
Hi Ian,

I'm confused here. She seems to visit a PHP written site, not a Rails site. Otherwise, your new link works (checked with dev tools).

**Comment by Gusbenz** [comment]
Nevermind. I got it. I never have used plans, so I had no idea you could customize it.

Thanks!
