### ISSUE TITLE
Allowing for responsive stylesheets by adding viewport meta tag

### ISSUE THREAD

**Issue by hannaliebl** [grinnellplans/GrinnellPlans#86]
I know a native mobile version of Plans is in the cards someday, but in the meantime if we want to have a stylesheet that includes media queries, we need to add one thing in the `<head>` tag of the template. See the [MDN explanation](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag#Viewport_basics) or [Bootstrap](http://getbootstrap.com/css/#overview-mobile). Namely, adding `<meta name="viewport" content="width=device-width, initial-scale=1">` or, arguably, `width` instead of `device-width`.

I made an [example](https://github.com/hannaliebl/mobile-plans) a while back of how a stylesheet could be mobile-friendly if we added that to the `<head>` (the JavaScript for the dropdown menus in my example is beyond the scope of this issue, but I bet I could do it in pure CSS at this point.)

Can we support this? I'm happy to work on this and making sure the default stylesheets work if we add the meta tag.

**Comment by iangreenleaf** [comment]
We can absolutely support this. Officially we're accepting no new features until launch, but if this is small and easy to implement, I'd probably make an exception.
