### ISSUE TITLE
MOTD

### ISSUE THREAD

**Issue by iangreenleaf** [grinnellplans/GrinnellPlans#95]
I've always thought it's bizarro that this is a separate page from just the [plans] plan. My intention is to have "root" (i.e. `http://www.grinnellplans.com/`) redirect logged-in users to that plan, and then we can do away with MOTD entirely. @ghadirim, does this sound good to you?

**Comment by ghadirim** [comment]
I agree with that. Its really just redundant.

**Comment by iangreenleaf** [comment]
Great. All that needs to be done on this is verify that this functionality is in place (I think it is, but not 100% sure).
